// Immediately Invoked Function Expressions (IIFE)

/* 
   TWO REASONS FOR IIFE:-
 
   1. KAI BAAR HAM AISI FILE LIKHTE HAI JISMEIN SIRF DATABASE CONNECTION HAI AUR HAM CHAHTE HAI KI HAM JAISE HI HAMARI
      APPLICATION START HO, WAISE HI HAMARA DATABASE KA CONNECTION START HO JAYE

   2. YA TOH GLOBAL SE POLLUTION NAHI CHAHIYE HAME => MATLAB AGAR HAMNE GLOBAL SCOPE MEIN KOI VARIABLE DECLARE KIYA HAI
      TOH WOH LOCAL SCOPE MEIN DIKKAT NA KARE
*/

// NAMED IIFE

(function chai(){
    console.log(`DB CONNECTED`);
}) () ; // YAHA SEMICOLON (;) LAGANA BAHOT ZAROORI HAI KYOKI AGAR HAM YEH NAHI LAGAYENGE
        // TOH aurcode() FUNCTION ERROR DEGA => BASICALLY HAM chai() KA EXECUTION STOP KARNE KE LIYE 
        // SEMICOLON (;) LAGA RAHE HAI

(function aurcode(){
    console.log("DB CONNECTED TWO");
}) () ; 

// ( ISMEIN FUNCTION DEFINITION AAYEGA ) ( AUR YEH FUNCTION CALL HAI YA FUNCTION KO EXECUTE KAREGA )


// HAM YAHA ARROW FUNCTIONS KA BHI USE KAR SAKTE HAI 
// LIKE IN THE BELOW FUNTION

// ( () => {
//     console.log('DB CONNECTED ARROW');
//     } ) ()

// UNNAMED IIFE

( () => {
    console.log(`DB CONNECTED THREE`);
}) ();

// UNNAMED IIFE WITH ARGUMENTS

( (name) => {
    console.log(`HELLO ${name}`);
}) ("Aman")

// NOTE:- IF YOU ARE WRITING TWO IIFE THEN USE SEMICOLON AT THE END OF THE FIRST IIFE